# Change these first
owner: Catacloud
repo: statuspage

sites:
  - name: Website
    url: https://www.catacloud.com
  - name: Web-app
    url: https://app.catacloud.com
  - name: Identity Server
    url: https://login.catacloud.com/.well-known/openid-configuration
  - name: GraphQL API
    url: https://api.catacloud.com

status-website:
  cname: status.catacloud.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Catacloud Statuspage
  introTitle: "Catacloud statuspage"
  introMessage: This is a statuspage for Catacloud services

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
