owner: Catacloud
repo: statuspage

sites:
  - name: Website
    url: https://www.catacloud.com
  - name: Web-app
    url: https://app.catacloud.com
  - name: Identity Server
    url: https://login.catacloud.com/.well-known/openid-configuration
  - name: GraphQL API
    url: https://api.catacloud.com

status-website:
  cname: status.catacloud.com
  logoUrl: https://app.catacloud.com/media/favicon/mstile-70x70.png
  faviconSvg: https://app.catacloud.com/media/favicon/safari-pinned-tab.svg
  favicon: https://app.catacloud.com/media/favicon/favicon-32x32.png
  name: Catacloud
  logoHref: https://www.catacloud.com
  introTitle: Live Service Status
  introMessage: This is a statuspage for Catacloud services
  theme: dark
